// <copyright file="CliDocEmitter.cs" company="Microsoft Corporation">
//     Copyright (c) Microsoft Corporation. All rights reserved.
//     Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
// </copyright>

using System.CommandLine;
using System.Text;
using Fhir.CodeGen.Common.Models;
using Fhir.CodeGen.Lib.Configuration;
using Fhir.CodeGen.Lib.Language;

namespace fhir_codegen_shared;

/// <summary>
/// Emits a Markdown description of the live <c>fhir-codegen</c> CLI surface.
/// </summary>
/// <remarks>
/// The emitter walks the <em>same</em> <see cref="LaunchUtils.EnabledCommands"/>
/// table and <see cref="ICodeGenConfig.GetOptions"/> pipeline the parser uses,
/// so the generated page cannot drift from the shipped binary.
/// </remarks>
internal static class CliDocEmitter
{
    private const string AutogeneratedBanner =
        "<!-- AUTOGENERATED by 'fhir-codegen docs cli' \u2014 do not hand-edit. -->";

    /// <summary>Emits the full CLI documentation page as a Markdown string.</summary>
    /// <returns>The generated Markdown content.</returns>
    internal static string EmitMarkdown()
    {
        StringBuilder sb = new();

        sb.AppendLine(AutogeneratedBanner);
        sb.AppendLine();
        sb.AppendLine("# Command Line Usage");
        sb.AppendLine();
        sb.AppendLine("This page is generated directly from the live `fhir-codegen`");
        sb.AppendLine("command tree, so the options listed here exactly match what the");
        sb.AppendLine("shipped binary accepts.");
        sb.AppendLine();
        sb.AppendLine("## Synopsis");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine("fhir-codegen [global-options] <command> [<sub-command>] [command-options]");
        sb.AppendLine("```");
        sb.AppendLine();

        // Global options (from ConfigRoot)
        sb.AppendLine("## Global options");
        sb.AppendLine();
        sb.AppendLine("These options apply to every command.");
        sb.AppendLine();
        AppendOptionsTable(sb, GetConfigOptions(typeof(ConfigRoot), excludeFromType: null));

        // Top-level commands
        foreach (LaunchUtils.LaunchCommandRecord rec in LaunchUtils.EnabledCommands)
        {
            sb.AppendLine();
            sb.AppendLine($"## {rec.Literal} \u2014 {rec.Description}");
            sb.AppendLine();

            List<ConfigurationOption> commandOptions =
                [.. GetConfigOptions(rec.ConfigurationType, rec.ExcludedConfigurationType)];

            if (commandOptions.Count > 0)
            {
                sb.AppendLine($"Options for `{rec.Literal}`:");
                sb.AppendLine();
                AppendOptionsTable(sb, commandOptions);
            }
            else
            {
                sb.AppendLine($"`{rec.Literal}` has no command-specific options beyond the globals.");
                sb.AppendLine();
            }

            // Language sub-commands
            if (rec.IncludeLanguageSubCommands)
            {
                foreach (ILanguage language in LanguageManager.GetLanguages().OrderBy(l => l.Name, StringComparer.OrdinalIgnoreCase))
                {
                    sb.AppendLine();
                    sb.AppendLine($"### {rec.Literal} {language.Name}");
                    sb.AppendLine();

                    List<ConfigurationOption> langOptions =
                    [
                        .. GetConfigOptions(LanguageManager.ConfigTypeForLanguage(language.Name), excludeFromType: null),
                        .. GetConfigOptions(rec.ConfigurationType, rec.ExcludedConfigurationType),
                    ];

                    if (langOptions.Count > 0)
                    {
                        AppendOptionsTable(sb, langOptions);
                    }
                    else
                    {
                        sb.AppendLine($"`{rec.Literal} {language.Name}` exposes no additional options.");
                        sb.AppendLine();
                    }
                }
            }

            // Manual (literal) sub-commands
            if (rec.SubCommands.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"### Sub-commands of `{rec.Literal}`");
                sb.AppendLine();
                sb.AppendLine("| Sub-command | Description |");
                sb.AppendLine("| --- | --- |");
                foreach ((string literal, string description) in rec.SubCommands)
                {
                    sb.AppendLine($"| `{literal}` | {EscapeTableCell(description)} |");
                }
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    /// <summary>Writes the generated Markdown to a UTF-8 (no BOM) file with a trailing newline.</summary>
    /// <param name="outputPath">The output file path.</param>
    /// <returns>0 on success.</returns>
    internal static async Task<int> WriteToFileAsync(string outputPath)
    {
        string content = EmitMarkdown();

        if (!content.EndsWith('\n'))
        {
            content += "\n";
        }

        string? directory = Path.GetDirectoryName(Path.GetFullPath(outputPath));
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        UTF8Encoding utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);
        await File.WriteAllTextAsync(outputPath, content, utf8NoBom);

        return 0;
    }

    /// <summary>
    /// Materialises a config object and returns its <see cref="ConfigurationOption"/> list,
    /// optionally filtering out properties inherited from a base type (mirrors the
    /// inheritance-exclusion behaviour of <see cref="LaunchUtils.BuildCliOptions"/>).
    /// </summary>
    private static IEnumerable<ConfigurationOption> GetConfigOptions(Type forType, Type? excludeFromType)
    {
        if (forType.IsAbstract)
        {
            yield break;
        }

        object? instance = Activator.CreateInstance(forType);
        if (instance is not ICodeGenConfig config)
        {
            yield break;
        }

        HashSet<string> excludedNames = [];
        if (excludeFromType != null)
        {
            object? excludeInstance = Activator.CreateInstance(excludeFromType);
            if (excludeInstance is ICodeGenConfig excludeConfig)
            {
                foreach (ConfigurationOption excluded in excludeConfig.GetOptions())
                {
                    excludedNames.Add(excluded.Name);
                }
            }
        }

        foreach (ConfigurationOption opt in config.GetOptions())
        {
            if (excludedNames.Contains(opt.Name))
            {
                continue;
            }

            yield return opt;
        }
    }

    private static void AppendOptionsTable(StringBuilder sb, IEnumerable<ConfigurationOption> options)
    {
        List<ConfigurationOption> opts = [.. options];

        if (opts.Count == 0)
        {
            return;
        }

        sb.AppendLine("| Option | Type | Default | Description |");
        sb.AppendLine("| --- | --- | --- | --- |");
        foreach (ConfigurationOption opt in opts.OrderBy(o => o.Name, StringComparer.OrdinalIgnoreCase))
        {
            Option cli = opt.CliOption;

            string aliases = cli.Aliases.Count > 0
                ? string.Join(", ", cli.Aliases.OrderBy(a => a.Length).Select(a => $"`{a}`"))
                : $"`--{cli.Name}`";

            string typeName = FormatTypeName(cli.ValueType);
            string defaultRendered = RenderDefault(opt.DefaultValue);
            string description = string.IsNullOrEmpty(cli.Description) ? string.Empty : EscapeTableCell(cli.Description);

            sb.AppendLine($"| {aliases} | `{typeName}` | {defaultRendered} | {description} |");
        }
        sb.AppendLine();
    }

    private static string RenderDefault(object? defaultValue)
    {
        if (defaultValue is null)
        {
            return "_(none)_";
        }

        if (defaultValue is string s)
        {
            return string.IsNullOrEmpty(s) ? "_(empty)_" : $"`{EscapeTableCell(s)}`";
        }

        if (defaultValue is System.Collections.IEnumerable enumerable and not string)
        {
            List<string> items = [];
            foreach (object? item in enumerable)
            {
                items.Add(item?.ToString() ?? "null");
            }

            return items.Count == 0
                ? "_(empty)_"
                : $"`[{string.Join(", ", items)}]`";
        }

        return $"`{EscapeTableCell(defaultValue.ToString() ?? string.Empty)}`";
    }

    private static string FormatTypeName(Type type)
    {
        if (type == typeof(string))
        {
            return "string";
        }

        if (type == typeof(bool))
        {
            return "bool";
        }

        if (type == typeof(int))
        {
            return "int";
        }

        if (type.IsArray)
        {
            return $"{FormatTypeName(type.GetElementType()!)}[]";
        }

        if (type.IsGenericType)
        {
            string genericName = type.Name;
            int tickIndex = genericName.IndexOf('`');
            if (tickIndex > 0)
            {
                genericName = genericName[..tickIndex];
            }

            string args = string.Join(", ", type.GetGenericArguments().Select(FormatTypeName));
            return $"{genericName}<{args}>";
        }

        return type.Name;
    }

    private static string EscapeTableCell(string value)
    {
        return value
            .Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r\n", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);
    }
}
